typography_spectrum: 0.8972263420000672
color:
  brandStrength: 0.02939489926211536
  lightness: 0.12020222120918334
  saturation: 0.09657199867069721
  rhythmicContrast: 0.9669156814925373
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.7653331176843494
author:
  name: John Shellard
  email: john.shellard@gmail.com
  url: johnshellard.net
name: 'Toleration, Religion, and the State'
title: The stuff we assume about the way things are
description: John Shellard
